### ISSUE TITLE
mpv script

### ISSUE THREAD

**Issue by phanirithvij** [kidonng/dotfiles#2]
Saw your mpv script and found it Interesting but it doesn't seem git clone is working

```
# In fish or bash I tried
git clone --filter blob:none https://github.com/{tomasklaen/uosc,po5/thumbfast}
```

and tree

```
.
└── https:
    └── github.com
        └── po5
            └── thumbfast
					**** uosc ****
```

uosc is cloned inside this weird thumbfast path

**Comment by kidonng** [comment]
Yeah rookie moment, this is actually `git clone <from> <to>`. Should have used a for loop.
